spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_base
    username: postgres
    password: root
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      use-new-id-generator-mappings: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  web:
    resources:
      cache:
        period: P10D
      chain:
        strategy:
          content:
            enabled: true
