name: Build Project
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Project
        run: ./mvnw clean --batch-mode install
      - name: Code Coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbious: true
          path_to_write_report: ./coverage/coverage-report.txt